spring:
  application:
    name: "configserver"
  profiles:
#    active: git
      active: native
  cloud:
    config:
      server:
#        git:
#          uri: "https://github.com/vuhv48/spring-config.git" #nho tao project moi tro toi day nhe
#          default-label: master
#          timeout: 5
#          clone-on-start: true
#          force-pull: true
        native:
#          search-locations: "file://.." config from a file
          search-locations: "classpath:/config"

server:
  port: 8071